### ISSUE TITLE
Incorporate new language translations

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#1157]
Add in support for two new languages (dutch and armenian)

**Dutch** - [WRI Translation NL.docx](https://github.com/wri/gfw-mapbuilder/files/5301566/WRI.Translation.NL.docx)
**Armenian** - [Forest watch_armenian and english.docx](https://github.com/wri/gfw-mapbuilder/files/5301602/Forest.watch_armenian.and.english.docx)

**Comment by eyosef** [comment]
Note to self;

- [x] implement translations
- [x] add `am: ''` where needed to avoid breaking app
- [x] make test build, confirm next steps (conduct workflow testing)

**Comment by eyosef** [comment]
<img width="719" alt="Screen Shot 2020-10-02 at 3 06 35 PM" src="https://user-images.githubusercontent.com/9040867/94960433-e066d680-04c0-11eb-8223-e0c795854123.png">
![Screen Shot 2020-10-02 at 3 06 50 PM](https://user-images.githubusercontent.com/9040867/94960444-e78de480-04c0-11eb-8a0f-6cfe717f78b1.png)

![Screen Shot 2020-10-02 at 3 09 10 PM](https://user-images.githubusercontent.com/9040867/94960630-3b003280-04c1-11eb-9b83-6ffcf1aca9ec.png)


Just a heads up that if an element doesn't have text, it's likely because it hasn't been configured in the country config
