### ISSUE TITLE
Hot Fix: Report does not work in Georgia Atlas

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#227]
https://atlas.mepa.gov.ge/map?l=en

The report is working in the Georgia atlas, but the analysis results are not visible. I think this is because some of the base configuration analysis might have been remove the json.

**Comment by richardbarad** [comment]
Hi @csphang,

Moving this into sprint 3. Let me know if you have the bandwith to work on it. 

Richard

**Comment by SwampGuzzler** [comment]
So, this issue is two-fold. Firstly, we have the fix! This can be tested at on [beta](https://beta.blueraster.io/mapbuilder/227-report-fix/external.html), where we can see that the report loads. 

However, we also still see a log-in modal which is prompted because one of our `extraLayers` points to this [legend service](https://gis.mepa.gov.ge/server/rest/services/legends/legends/MapServer), which requires a login. When this is also fixed (probably by @richardbarad on the `portal` side), the whole thing will work!

**Comment by richardbarad** [comment]
Thanks @SwampGuzzler. I just updated the legend service to point to a public one.

**Comment by richardbarad** [comment]
@SwampGuzzler and @csphang,

I realized this was in sprint 3, but do you think we can merge it into sprint 2 and include it in the deployment we make after thanksgiving?

**Comment by richardbarad** [comment]
Hi @csphang and @SwampGuzzler,

I wanted to check if this was included in the 1.3.1 release? It looks like the report in the Georgia site is still not working. 

Thanks!

https://atlas.mepa.gov.ge/map

Richard

**Comment by SwampGuzzler** [comment]
@richardbarad You are right! I just added an additional fix that you can confirm [here](https://beta.blueraster.io/mapbuilder/227-report-sharinghost/external.html) and am thinking this might merit a quick `1.3.2` release so we can fix this thing once and for all. This fix is in #300

**Comment by richardbarad** [comment]
Look good @SwampGuzzler! There are a few other small things I think we should try to fix in a 1.3.2 release and hopefully do a release sometime next week. Let's chat about it during our meeting on Monday.
