### ISSUE TITLE
CSS updates to Analysis Panel

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#276]
The analysis panel requires a few CSS style updates. Specifically:

1. The end year is fully visible in the time-slider as seen below. 

![image](https://user-images.githubusercontent.com/40440743/48984309-174f5280-f0c8-11e8-82b6-6e179bb30f9d.png)

2. When opening the date selector on a small screen the date selector is not fully visible and is hidden behind the panel. Can we update it so that it so that the date selector opens up above the layer panel?

![image](https://user-images.githubusercontent.com/40440743/48984324-41a11000-f0c8-11e8-9cf7-d986542bfce6.png)

**Comment by jenboyd** [comment]
@csphang CSS updates can be tested here:
http://alpha.blueraster.io/gfw-mapbuilder/276-analysis-css-fix/external.html

Changing the date selector to open outside of the layer panel isn't very straightforward, but I updated it so that it will only ever open below and will always be visible because of the scroll. Let me know what you think.

**Comment by richardbarad** [comment]
@jenboyd 

Thanks! I think this works fine! 

However, it seems that when you open the popup inside of the window and that causes the scroll to open the scroll does not work. I am attaching a video showing this behavior.

Best,

Richard
[Select_range_popup.zip](https://github.com/wri/gfw-mapbuilder/files/2646476/Select_range_popup.zip)

**Comment by jenboyd** [comment]
Updated!
