### ISSUE TITLE
Add download feature for the Vega analysis charts (.img, .csv)

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#287]
Enable users to download the resulting vega visualization as a graph (image), and data (.csv) format.

#### Link that may help:
- https://vega.github.io/vega/usage/
- Noticed on the flagship site that the data download for .csv makes a call to the GFW API. Sample call to download GLAD alert results: 

https://production-api.globalforestwatch.org/glad-alerts/download/?period=2015-01-01,2018-12-07&gladConfirmOnly=False&aggregate_values=False&aggregate_by=False&geostore=78df1a0bb7e63561d2d494c4b7daa89c&format=csv

**Comment by jenboyd** [comment]
Can be tested here: http://alpha.blueraster.io/gfw-mapbuilder/287-vega-chart-download/external.html

**Comment by richardbarad** [comment]
@csphang, @SwampGuzzler, @KaylaKremer,

Just to follow up on this task based on our discussion yesterday. It looks like Jennifer implemented the following:

1. Download Vega Image as a PNG

2. Download JSON data using the download endpoint from the API (e.g: https://production-api.globalforestwatch.org/glad-alerts/download/?period=2015-01-01,2019-04-26&gladConfirmOnly=False&aggregate_values=False&aggregate_by=False&geostore=5ae1ef380c77ea0ee33915575c306a12&format=json) 

3. Download JSON data using the download endpoint from the API (e.g: https://production-api.globalforestwatch.org/glad-alerts/download/?period=2015-01-01,2019-04-26&gladConfirmOnly=False&aggregate_values=False&aggregate_by=False&geostore=5ae1ef380c77ea0ee33915575c306a12&format=json)

For our purposes I think we can remove JSON since most users will not know what to do with a JSON file. Also, we should note that only the GLAD Alerts endpoint and fires have a download API endpoint. The download returns the actual point data. For the others, we need to disable the API download option since there is no endpoint.

Also, is it possible to download the data directly from the a VEGA table. This could be one option for allowing downloads in the other analysis which do not have a download endpoint. In all the Vegas I [created](https://github.com/wri/gfw-mapbuilder/projects/9) I included a table called `table` which has an appropriate structure for downloading. Possible to download data from VEGA tables? This is not as much of a priority but just curious if we think it is possible?

**Comment by SwampGuzzler** [comment]
1. Remove the `Download Data as JSON` option
2. Switch the call from `production-api.globalforestwatch.org/ourLayerEndpoint/download/` to `production-api.globalforestwatch.org/ourLayerEndpoint/?queryParams...&table=true` then crunch those numbers together and output them as a CSV to immediately download

**Comment by richardbarad** [comment]
For now, we will just do downloads from the API for GLAD Alerts and Fires.

**Comment by SwampGuzzler** [comment]
ALL analyses
- download png image of chart

GLAD Alerts Badge Chart
- download data via A[PI endpoint](https://production-api.globalforestwatch.org/glad-alerts/download/?period=2015-01-01,2019-04-26&gladConfirmOnly=False&aggregate_values=False&aggregate_by=False&geostore=5ae1ef380c77ea0ee33915575c306a12&format=csv)

**Comment by KaylaKremer** [comment]
@richardbarad Test build for this ticket is here: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/287-download-feature-for-vega-charts/external.html

**Comment by richardbarad** [comment]
1. Please change the text to say "Download PNG", for the image.

2. Change the text to say "Download Alerts as .CSV" for GLAD Alerts.

3.  Please review the design in the report pages. Right now, it looks a little odd. See screenshot below:

![image](https://user-images.githubusercontent.com/40440743/58658088-bc541d80-82ed-11e9-8406-b43f34a9e595.png)

I suggest we go for a similar design to the Layout panel. Can we also hide the download icon untill the analysis finishes? 

4. I noticed we added Fire Alerts downloads as .csv which is great. However, the call to the Carto API is not working because it includes https://production-api.globalforestwatch.org at the front of it.

**Comment by richardbarad** [comment]
One more comment, the GLAD Alert looks like it does not include a .csv in the file name. I realize this is an issue from the API side, but wondering if we can force the file type to be a .csv?

Richard

**Comment by KaylaKremer** [comment]
@richardbarad Test Build: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/287-download-feature-for-vega-charts/external.html

**Comment by richardbarad** [comment]
@KaylaKremer. This looks good! I would like to test on several of our atlas configurations. Please see my comment here: https://github.com/wri/gfw-mapbuilder/issues/286

Maybe we can test the download at the same time as the other VEGA work since it looks like everything may have been merged together.

**Comment by richardbarad** [comment]
I tested this in the builds you put up here https://github.com/wri/gfw-mapbuilder/issues/286 and this looks good! 

One small comment, the GLAD Alerts download as a .csv has a size restriction. Currently, if you draw an area which is too large it returns an error messaging indicating that "Geometry is too large for custom stats/download. Please try again with a smaller area of interest". Is there a better way to handle this error message? I see two options:

1) Show an error message in the layer panel

2) Disable the download option if the area is above the size threshold. I believe it is 1mio ha but need to double check with Vizz.

Attaching a video showing what currently happens. 
[GLAD_download_API.zip](https://github.com/wri/gfw-mapbuilder/files/3267257/GLAD_download_API.zip)

**Comment by KaylaKremer** [comment]
@richardbarad I made a new build with the error handling you described. Let me know if this is what you wanted! https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/287-new-download-build/external.html

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks!

It looks like we are blocking analysis and download. We should always allow analysis, but block downloads when the area too large. Did you implement the size restriction? I am noticing that on some shapes I am able to fires up an analysis but the download still does not work. Maybe we have the restriction wrong. I can follow up with Vizzuality on this. 

**For now, could we consider one of the following options?**

1) Always allow analysis, but if the area is too large and returns an error upon download show the error message in the layer panel. (Would you need to know the size restriction to properly implement this)?

2) A even more simpler solution, would be to open the download link in a new tab. If the user get's an error they will see it in a new tab and still be able to return to their map. It looks like this is how flagship handles this. Attaching a video of the workflow on flagship.

[flagship_download.zip](https://github.com/wri/gfw-mapbuilder/files/3276729/flagship_download.zip)

**Comment by KaylaKremer** [comment]
@richardbarad I based the error handling on the size of the response json data returned. I tried to guess at which size it seems to fail for the csv. I came to around 400, so I created an error handle that if the json data length is greater than this, display the error. But since I don't know the exact number which triggers the csv to fail and display the error message, that would be something to ask Vizzuality about if you think they would know.

So yes, for option #1, I would need to know the size restriction to properly implement this. I can also set it up to where the chart will still display, but can also feature an error message saying it can't be downloaded. I can also easily implement option #2. Just let me know which option you'd like me to implement!

**Comment by richardbarad** [comment]
@KaylaKremer. let's implement #2 for now.

**Comment by KaylaKremer** [comment]
@richardbarad Here is a new build which opens the CSV file in a new tab: https://alpha.blueraster.io.s3.amazonaws.com/gfw-mapbuilder/287-csv-new-tab/external.html

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!
