### ISSUE TITLE
Support custom basemaps

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#318]
Support additional basemaps! Several use cases:

1. User has a basemap in different language
2. User creates their own basemap and would want to see it
3. User selects an Esri Basemap not normally a part of MapBuilder (for example, topographic)

**Comment by richardbarad** [comment]
Hi @csphang,

For India here is the basemap they would like to use: http://gfw.maps.arcgis.com/home/webmap/viewer.html?webmap=acb6f60ce2fe469c9a1aa92de084c264

Just wanted to make sure we are on the same page regarding our approach here. 

I think we could have mapbuilder set up such that mapbuilder defaults to whatever basemap is used in the webmap even if it is a custom one and the name used is the same name specified in the basemap? 
The main question I have is how do we approach getting a thumbnail for custom basemaps. Any ideas?

Also, if they want to have a 2nd custom basemap could they specify it in the configuration file? If so, would  it be better to point to an ArcGIS webmap congaing a basemap or point directly to tiles or web service?

Best,

Richard

**Comment by csphang** [comment]
@richardbarad Want to confirm we're interpreting this correctly! Would you want **both** the topographic and the India Boundary layers as the basemap? Or just the India Boundary layer? In this India example, neither the Topographic nor the India boundary are in our current Basemap options. But what about the scenario where a user has a webmap with two basemap layers and one layer is already supported (for example, India Boundary and Imagery)? Would the app display the same way and include both layers as the basemap?

![2019-01-28_13-40-37](https://user-images.githubusercontent.com/13664037/51858856-b7fa0280-2303-11e9-8807-69b2f155ac6c.jpg)

**Comment by richardbarad** [comment]
@csphang,

Let me check with the India to confirm but I think they would want to show both the topographic and the India boundary layers.

**Comment by richardbarad** [comment]
Hi @csphang,

Confirming that the India team would like to use both layers as the basemap.

**Comment by SwampGuzzler** [comment]
@richardbarad Check out a build addressing this [here!](http://alpha.blueraster.io/gfw-mapbuilder/318-custom-bm/external.html)

I would still like to see a webmap with other custom basemaps for more ways to test my fix, do you know of any other builds like this?

**Comment by richardbarad** [comment]
Thanks @SwampGuzzler.

It looks like the White India layer is showing up on top of the other layers instead of as part of the basemap.

You can also try out this one: https://gis.mepa.gov.ge/portal/home/item.html?id=62252059221f4276bbe27b3d038e3c7c

It is a version of the WRI Mono basemap with the characters in the local langauge instead of English.

It also hosted on portal so will let us test out portal: https://gis.mepa.gov.ge/portal/home/item.html?id=62252059221f4276bbe27b3d038e3c7c

Here is another one you can test with. This webmap is hosted on a french ArcGIS Online so the basemap is called topographie, even though it uses the standard topographic basemap. http://gfw.maps.arcgis.com/home/webmap/viewer.html?webmap=0bc13b8260c74eb9a30de3e5d3ccd64e

This was the issue we had here: https://github.com/wri/gfw-mapbuilder/issues/210

**Comment by csphang** [comment]
Thanks @richardbarad, we will test this out with the two examples from your message!

**Comment by SwampGuzzler** [comment]
This ticket is being hoisted into the next release: [v1.4.0](https://github.com/wri/gfw-mapbuilder/projects/9) (AKA sprint 4) per @csphang !

**Comment by richardbarad** [comment]
Thanks for your work on this @SwampGuzzler! 

As discussed with @csphang let me know if there is a specific deployment setup which is causing issues and if we can try to simplify this feature request. For example, I would be fine with having the [India basemap](http://gfw.maps.arcgis.com/home/webmap/viewer.html?webmap=acb6f60ce2fe469c9a1aa92de084c264) be called something other than topographic if that helps simplify the feature request.

If it is something related to a specific application, then I am I not sure if we should spend to much time on it so that we can focus on features which are relvant to all apps.

**Comment by SwampGuzzler** [comment]
@SwampGuzzler --> Per your own worry: all of the potential use-cases/setups are In This Ticket!

**Comment by richardbarad** [comment]
@SwampGuzzler & @csphang . Just updating this ticket to try to properly include all the main use cases we should address!

1) [Webmap](https://www.arcgis.com/home/item.html?id=0bc13b8260c74eb9a30de3e5d3ccd64e) is hosted on a non-English ArcGIS Online account. This webmap has a basemap called Topographie which is the standard topograhic basemap, but the MapBuilder based on this map does not load the topographic basemap. http://cog.registreredd.org/PP-redd/map

2) The India team would like to include a "Mask" layer in their basemap which shows a white background for India. This is because they do want labels from the basemap to be visible. Here a link to a webmap: https://www.arcgis.com/home/item.html?id=2dc7885a51544695bc4b08d21d878586. You will see that there is a layer called India Boundary has been added to the basemap and bothe layers should be part of the basemap.

As discussed, we can rename the custom basemap to something other than topographic in the India web map if that will help with this use case! 

Richard

**Comment by richardbarad** [comment]
@csphang, looking at if we can use a customized vector tile basemap in which the label visibility has been customized.

**Comment by csphang** [comment]
Hi @richardbarad - We tested the vector tile basemap workflow and it does not work out of the box. So we'll need to dig into this ticket tomorrow with the original workflow!

**Comment by csphang** [comment]
Add a boolean True/False to the constructor parameters that would allow users to use their webmap basemap as opposed to the WRI basemaps or Esri basemaps. We will need to add a generic thumbnail image for custom basemaps and use the name from the Basemap in AGOL for the custom basemap title.

**Comment by SwampGuzzler** [comment]
@richardbarad @csphang We can test these combinations out here: 
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/topographie/
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/india-mask/
- http://alpha.blueraster.io/gfw-mapbuilder/318-inherit-basemap/generic/ (`useWebmapBasemap: false`)

**Comment by SwampGuzzler** [comment]
A note: `useWebmapBasemap` will be **false** by default

**Comment by richardbarad** [comment]
@SwampGuzzler. Looks good! Just to confirm, is this over-writable using ArcGIS Online appids? 

Could you also work with @csphang to test to see if this allows support for customized ArcGIS Online vector tile basemaps?

Richard

**Comment by csphang** [comment]
Icon for custom basemap:
![Custom_Basemap_Icon](https://user-images.githubusercontent.com/13664037/66676221-f555b480-ec34-11e9-98a5-4c4fc4466bd9.png)

**Comment by richardbarad** [comment]
@csphang. Can we remove the person?

**Comment by csphang** [comment]
@richardbarad the thought behind it is that the user icon denotes the user is the “owner/creator” of that basemap. Hopefully that helped? Let us know if you'd prefer to still remove the person

**Comment by richardbarad** [comment]
@csphang. I think we can remove it, since the people. I thought it might confuse users of the actual map who did not participate in building the platform.

**Comment by SwampGuzzler** [comment]
@richardbarad The ArcGIS Online `appid` settings will overwrite! So if the app in AGOL has a `useWebmapBasemap` set to true, then we will, etc.

**Comment by SwampGuzzler** [comment]
@richardbarad The Custom Basemap `icon` has been updated!

**Comment by SwampGuzzler** [comment]
@richardbarad When I look at that application's `source` I do not see the **useWebmapBasemap** parameter - how is it being inserted?

**Comment by richardbarad** [comment]
@SwampGuzzler. I am testing outside of the CMS, since the field still needs to be added to the CMS. Please take a look at the attached file in the zip folder. I added **useWebmapBasemap** on line 38 of the configuration. Let me know if something is not correct.

**Comment by SwampGuzzler** [comment]
@csphang http://alpha.blueraster.io/gfw-mapbuilder/318-basemap-india-update/ --> An update that works for both of the India configurations and Topographie as well!

**Comment by csphang** [comment]
@SwampGuzzler Looks good! @richardbarad this is ready for your review and testing at the link above. We'd like you to take a look before we merge it in with the consolidated build.

**Comment by richardbarad** [comment]
@csphang. Looks good!

**Comment by richardbarad** [comment]
I believe we had discussed pulling the name of the custom basemap from the webmap. It looks like this still needs to be deployed.

**Comment by SwampGuzzler** [comment]
@richardbarad Done! That build is now inheriting the webmap group title @csphang
