### ISSUE TITLE
Settings: Implement ability to adjust settings for charts

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#391]
Note that this will not apply to any charts w/ONLY a geostore parameter. This includes:
- Land Cover Composition
- Fire Alerts
- Country specific analyses
- GLAD ALerts per month

**Comment by KaylaKremer** [comment]
@csphang @richardbarad Could either of you provide more specifics? Lucas and I weren't entirely sure what this ticket means.

**Comment by richardbarad** [comment]
@KaylaKremer,

The idea here is to be able to modify the analysis setting in the report for analysis which have UI params in the analysis configuration. For example, for the annual tree cover loss a user should be able to modify the date range and Tree Cover threshold just like they can when running the analysis in the layer panel as shown below:

![image](https://user-images.githubusercontent.com/40440743/60942670-70fc3a00-a2b1-11e9-8c2f-3a8b724667da.png)

The option to change settings would be available when you click on the settings button for the analysis. For analysis which do not have UI params we would not enable this option since there are no settings to change.  

Let me know if anything is not clear of if you need any additional information!

**Comment by KaylaKremer** [comment]
@richardbarad Thanks for the clarification!

**Comment by SwampGuzzler** [comment]
@KaylaKremer We still need to support the **Calendar** UI Param for widgets like `Total GLAD Alerts`!

**Comment by SwampGuzzler** [comment]
There are a couple more nitpicks in the `comments` on PR #456

**Comment by SwampGuzzler** [comment]
<img width="353" alt="Screen Shot 2019-07-31 at 4 22 26 PM" src="https://user-images.githubusercontent.com/5713523/62245364-7c71eb00-b3af-11e9-9d89-743fefabffa7.png">
<img width="376" alt="Screen Shot 2019-07-31 at 4 22 47 PM" src="https://user-images.githubusercontent.com/5713523/62245367-7f6cdb80-b3af-11e9-93b9-132f3de37ef8.png">
@KaylaKremer For our calendar `previous` and `next` buttons, these generic **a** tags have styles! We need to make them more specific: 
`.class-i-care-about > a` or something!

**Comment by csphang** [comment]
![2019-08-20_15-25-33](https://user-images.githubusercontent.com/13664037/63377813-ccb0ed00-c35e-11e9-8739-8c3e999ee747.png)
