### ISSUE TITLE
For selected features on map, retain attribute table

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#394]
If users select an existing feature on the map, render the table before the first category of charts (Forest Change)

**Comment by SwampGuzzler** [comment]
Use our old `addTitleAndAttributes` function and all of its logic, but put it inside of a new *component*!

Inside of this *ReportTable.js*, let's steal a lot of the `queryTask` execution and `infoTemplate` validation, but instead of a lot of `appendChild` document methods, let's just use react for everything!

**Comment by csphang** [comment]
Verified. Tested on country consolidated builds. For example, Cameroun:
http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/atlas-forestier-cameroun/

![2019-08-20_14-46-57](https://user-images.githubusercontent.com/13664037/63375237-61b0e780-c359-11e9-93a1-daafa633fbda.png)
