### ISSUE TITLE
(Chart badges): smaller max width

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#436]
- Keep badge charts same width as you resize
- Make charts which resize have same max-width as the textbox with metadata.

**Comment by richardbarad** [comment]
@KaylaKremer and @csphang.

Just flagging that we will need to make sure we have a scale-able solution here as well, since we have custom country analysis which uses a VEGA badge. For example, the `Total area with combined potential` analysis in the Ethiopia restoration atlas: [http://eth.restorationatlas.org/atlas](http://eth.restorationatlas.org/atlas)

**Comment by richardbarad** [comment]
**From Slack:** from @KaylaKremer:

If we hardcode the width and heights, wouldn't that make it not responsive at all? I'll first try to set the max-width on the container so that it can shrink and expand up to that max size. If that doesn't work, then the next best thing would be to hardcode width / height.

I do think for the badge chart inner text, that will always need to be hard coded since I can't control it with CSS. Just like how you did for the pie chart by removing any addition and only keeping division, I think that will also place the badge text perfectly in the center!

@richardbarad to update current badges to only use division in text placement.

**Comment by csphang** [comment]
@richardbarad I think the chart badges are looking great. If they meet your approval in the consolidated builds, please move this to Reviewer Approved!

You can test on any of the consolidated builds. Example, http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/tierras-indigenas/

![2019-08-20_14-59-29](https://user-images.githubusercontent.com/13664037/63376181-30d1b200-c35b-11e9-8c38-dfc6db814751.png)

**Comment by richardbarad** [comment]
@csphang. This looks good. Thanks!
