### ISSUE TITLE
Design for measurement tool

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#458]
![Measurement_Shape](https://user-images.githubusercontent.com/13664037/63031122-856bbd80-be81-11e9-95e9-576e58f345e7.png)
![Measurement_Line](https://user-images.githubusercontent.com/13664037/63031123-856bbd80-be81-11e9-8162-d07841d6472c.png)

**Comment by richardbarad** [comment]
We also talked to Manny about the design for the measurement tool, and he is going to check with Rachel to see if she worked on it. If not, design can prepare a new design this week to have ready for development in next phase. 

**Agreed that:**

•	It would be best to move the measurement tools to the right hand side and remove the home button
•	Drop coordinates and only have area / distance tools
•	Have a small modal that opens up on the right hand side to adjust the units and select between distance and area measurement tools.

**Comment by richardbarad** [comment]
Design comments:

- Make measurement box smaller
- Remove the text which says measurement result
- Look at the positioning of the modal since it currently overlaps with space allocated to the legend

![image](https://user-images.githubusercontent.com/40440743/64207820-6605f600-ce6b-11e9-9721-76a9b0bd0924.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

I have a few clarification questions for this ticket. 

1. Should I position the measurement modal to be to the left of the tools panel?  I agree with you that it will overlap the legends panel if it's below. Also, should it be like that for mobile too?

2. The other modal windows, such as print, draw tools, etc. allow the user to close it with the 'x' button. Should the measurement modal have this as well? Currently I have kept it, as shown in the screenshot below.

3. I have made the modal a lot smaller like you requested. However, I think the "Measurement Result" text should remain only because if it's removed, it will be blank space before the user has measured anything and I think it might be confusing for them. I can make the text much smaller so it takes up less space. What do you think?

<img width="262" alt="Screen Shot 2019-09-16 at 12 05 20 PM" src="https://user-images.githubusercontent.com/22095244/64974323-93df3780-d87a-11e9-9049-55b340d5730a.png">

**Comment by richardbarad** [comment]
@KaylaKremer 

1) yes, I think to the left is fine for both desktop and mobile.

2) Yes, let's add an x button

3) I think we can keep Measurement Result, as it looks better with you new design. What you proposed sounds like a good way to move forward.

**Comment by KaylaKremer** [comment]
@richardbarad 

Great, will do! I hope to have a build up for you soon for this, possibly today!

**Comment by KaylaKremer** [comment]
@richardbarad 

Here's the build!  http://alpha.blueraster.io/gfw-mapbuilder/458-measurement-tool-redesign/

**Comment by richardbarad** [comment]
@KaylaKremer. Please see my comments below!

1) The box changes size size when you change the units to a unit format which is longer than the dropdown area. For example, see screenshot below for Kilometers and Miles as Units. Can we configure it so that the units dropdown does not jump down to another line when you change units?

![image](https://user-images.githubusercontent.com/40440743/65191066-d18dbd00-da40-11e9-84c2-262e8a644d01.png)
![image](https://user-images.githubusercontent.com/40440743/65191073-d7839e00-da40-11e9-9656-81c976927a8f.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

1. Yes, I can definitely fix this!

2. Yes, I can also add the delete! Before I go ahead and implement this, I just wanted to make aware that the default behavior for the Esri widget is to delete shape when you switch measurement tools by clicking on another button or if you click on your currently selected measurement tool to de-select it. I also have it set up to clear the shape if you click on the 'x' button as well as when you click on the measurement tool itself again. So basically, adding the 'delete' button would be repeating functionality and I wasn't sure if that would be more confusing to the user?

If you still think it's best to have it, then how about styling the 'delete' the same way I set it up to remove coordinates?

![Screen Shot 2019-09-19 at 9 42 31 AM](https://user-images.githubusercontent.com/22095244/65249387-e52d3800-dac1-11e9-9dc9-c5807174571a.png)

3. I will look into this! Thanks for the video.

**Comment by KaylaKremer** [comment]
@richardbarad ,

Build has been updated: http://alpha.blueraster.io/gfw-mapbuilder/458-measurement-tool-redesign/

It should no longer select features when you use the measurement tool and I fixed the styling issue of the dropdown wrapping to the next line. Let me know what you think and if you still want the delete button after what I mentioned above!

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks! I think this looks good. No need to add the delete button!
