### ISSUE TITLE
Implement redesign for multiple selected features

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#461]
[Layer_Navigation (3).pdf](https://github.com/wri/gfw-mapbuilder/files/3547922/Layer_Navigation.3.pdf)

**Comment by KaylaKremer** [comment]
@richardbarad ,
Test Build: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign/

**Comment by richardbarad** [comment]
@KaylaKremer & @csphang. Please take another lock at the mockup provided by the design team. I think there is an inconsistency between the design and how this feature is implemented in the build above. In the build above, the dropdown lets you select between features. 

However, in the mock-up the dropdown let's you toggle between **layers** & clicking on the next button lets the user switch between feature if multiple features are selected in the same layer.

**Comment by csphang** [comment]
- [ ] Dropdown -- display layer names (`count of features` e.g. 5)
- [ ] If a user closes out of a feature via "x" button and there is only 1 feature in that layer, then it should default to the next layer set

**Comment by KaylaKremer** [comment]
@richardbarad ,

I've updated the build: http://alpha.blueraster.io./gfw-mapbuilder/461-multiple-selected-features-redesign/

Hopefully, everything now works as expected according to the comp!

**Comment by SwampGuzzler** [comment]
<img width="519" alt="Screen Shot 2019-10-03 at 12 05 44 PM" src="https://user-images.githubusercontent.com/5713523/66144208-66aebb00-e5d6-11e9-92f1-3074743ea729.png">

@KaylaKremer  See the `2/1` on this layer?! We need just the `1/1`!
Workflow: **X** out a feature that was the only feature in a layer, which took me to the first feature in the next layer (which had two features), I then selected another feature from a different layer (with only one feature), and instead of showing `1/1`, we saw `2/1`!

**Comment by SwampGuzzler** [comment]
@KaylaKremer On 'NEXT', our `index` remains the same:
<img width="556" alt="Screen Shot 2019-10-03 at 12 09 33 PM" src="https://user-images.githubusercontent.com/5713523/66144494-efc5f200-e5d6-11e9-867e-73734ee406fb.png">

**Comment by richardbarad** [comment]
@KaylaKremer & @SwampGuzzler. Moving this back to in progress until issue identified by Lucas is fixed!

**Comment by KaylaKremer** [comment]
@richardbarad Could you test out this new build ? 

http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign/

Apologies for this ticket taking so long to complete. It has proven to be one of the most complex ones yet besides the fires bug to complete! We should make sure to thoroughly test it out since there are many ways the user can interact with this For example:

1. Just clicking on different features on the map
2. Click on the map to select feature, then using the prev/next buttons
3. Click on the map to select feature, click prev/next buttons, click on map again
4. Click on the map to select feature, click prev/next buttons, select dropdown option, use prev/next buttons again
5. Click on the map to select feature, click prev/next buttons, select dropdown option, use prev/next buttons again, click on map again to select different feature
6. Repeat 4 -5, but use dropdown first before interacting with next/prev buttons.

I'm sure I'm missing a few workflows, but this is the general idea.

**Comment by richardbarad** [comment]
@KaylaKremer. I'll test on Monday as I am on leave this afternoon. @csphang, please test if you have time today,

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good! Do you mind putting up another build which uses the configuration for our Georgia atlas. Attached is the JSON.
[GEO.zip](https://github.com/wri/gfw-mapbuilder/files/3697674/GEO.zip)

**Comment by richardbarad** [comment]
@KaylaKremer. Just found 1 small bug. 

If I)

1) Click in an area which results in selecting **two** features from the same layer.

2) Toggle to the layer containing two features using the dropdown

3) Click on the x icon the layer panel will jump to a feature in a different layer instead of going to the next feature in the same layer. 

Attached is a video of workflow.In the attached video, two features get selected from the Concession Forestière layer. After toggling to the Concession Forestière and clicking the x the layer panel goes to a different layer instead of going to the next feature in the Concession Forestière layer.

[Layerbug.zip](https://github.com/wri/gfw-mapbuilder/files/3697717/Layerbug.zip)

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I don't believe that is a bug. When you click the 'x', it causes the tracking index to go down by 1. If you are at the first feature in a layer and click the `x`, you then jump to the next layer group because you can't go down further in the list of features in the current layer (i.e. you can't go to feature 0 of 2, -1 of 2, etc).

**Comment by richardbarad** [comment]
@KaylaKremer. Ok. I see what you mean. 

I was thinking that if your layer contained multiple active features you would always go to the next or proceeding feature in that layer, unless the value was set to `1/1`. Would that significantly complicate things? If yes, I think we can stick with the current setup!

Richard

**Comment by KaylaKremer** [comment]
@richardbarad , I'll see what I can do! But yes, this may significantly complicate things. I'll work on this now and can let you know at our meeting today how it goes.

**Comment by KaylaKremer** [comment]
@richardbarad I asked Lucas about this and he thinks we should add this to the backlog for something we could improve upon later. Would that be ok with you?

**Comment by richardbarad** [comment]
@KaylaKremer. Sounds good!

**Comment by richardbarad** [comment]
Let's please put up a build for Georgia as well just to make sure we have rigorous testing on this!

**Comment by KaylaKremer** [comment]
@richardbarad , sure, I'll make a Georgia build now!

**Comment by KaylaKremer** [comment]
@richardbarad Georgia build: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-georgia-build/

**Comment by richardbarad** [comment]
@KaylaKremer. Finding one bug which is present in both DRC & Georgia builds when you translate the app.

1) If I load: http://alpha.blueraster.io/gfw-mapbuilder/461-multiple-selected-features-redesign/

2) Use the toggle to change the language to to the secondary langauge

3) Click on a shape in the map.

The application does not open up the data tab, and instead shows the prompt asking the user to click on an areas. Please see attached video.
[language_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3698952/language_bug.zip)

**Comment by KaylaKremer** [comment]
@richardbarad Builds have been updated again to fix the language toggle issue.

**Comment by richardbarad** [comment]
Looks good!
