### ISSUE TITLE
The loading icon is not visible for annual TCL Analysis.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#470]
When loading the report, the spinning circle indicating that the analysis is loading is not visible. This issue is only present for the Annual TCL Analysis. Attached is a video and screenshot below showing a loading circle for the analysis above the Annual TCL Analysis but not for the annual TCL analysis.

![AnnualTCL_Analysis](https://user-images.githubusercontent.com/40440743/62320797-2c5a5d80-b46f-11e9-92fb-941cabb40513.png)

[AnnualTCLanalysis.zip](https://github.com/wri/gfw-mapbuilder/files/3458304/AnnualTCLanalysis.zip)
reenshot below.

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

I see what you mean about the loader not displaying for the Annual TCL Analysis. I think what is happening is that it is working just fine, but there is a little bit of a lag in the `canvas` element rendering the chart on the DOM. The loading icon is set to turn off once the request for the vega chart config comes back and the function that makes the vega chart is successfully called. (It is also set to turn off if the request fails in order to display the error message). 

I'm not sure if there is a way to tell if the chart is displaying inside the `canvas` element or not. If there is, I could set the loader to turn off then. I will ask @SwampGuzzler about this today!

**Comment by richardbarad** [comment]
Hi @KaylaKremer,

Thanks for the clarification. 

I just checked this build http://alpha.blueraster.io/gfw-mapbuilder/452-update-resources-to-distinguish-chart-types/ and it looks like I am not seeing the analysis loading icon even while the request is still pending. In the screenshot below, we see that the umd-loss endpoints are both still pending but the loader does not display for the Annual TCL Analysis!

![AnnualTCL_Analysis](https://user-images.githubusercontent.com/40440743/62374042-10a39580-b509-11e9-8088-e42c03b8d49e.png)

**Comment by KaylaKremer** [comment]
@richardbarad , I think I fixed the issue! Can you test it out with this build? http://alpha.blueraster.io/gfw-mapbuilder/470-loading-icon-not-visible-for-TCL-analysis/

**Comment by richardbarad** [comment]
@KaylaKremer. Looks good!
