### ISSUE TITLE
(Mobile): Increase width of header

### ISSUE THREAD

**Issue by csphang** [wri/gfw-mapbuilder#502]
Report header on mobile appears pretty small! Are we able to bump it up to match the header size we have on the map view on mobile?

![Screenshot_20190819-173740](https://user-images.githubusercontent.com/13664037/63301391-636ea280-c2a8-11e9-876f-1e9b7f7b6093.png)

**Comment by KaylaKremer** [comment]
@csphang  

Here is the build: http://alpha.blueraster.io/gfw-mapbuilder/502-increase-header-size/

I noticed that in your original screenshots, it was still displaying with the desktop styles, not the mobile styles I had made. I went ahead and increased the size of the header as well as the buttons to make it easier for the user to tap on. It appears like this on my local when using the iPhone 6 mobile size as an example:

<img width="360" alt="Screen Shot 2019-08-20 at 3 03 19 PM" src="https://user-images.githubusercontent.com/22095244/63376523-03393880-c35c-11e9-824f-ad2bc8e447d1.png">

<img width="393" alt="Screen Shot 2019-08-20 at 3 03 11 PM" src="https://user-images.githubusercontent.com/22095244/63376532-07655600-c35c-11e9-9923-732b3ee357d9.png">

For the build, I noticed that it still retains the desktop styles:

<img width="879" alt="Screen Shot 2019-08-20 at 3 06 38 PM" src="https://user-images.githubusercontent.com/22095244/63376597-324faa00-c35c-11e9-8790-644e486c0937.png">

Not sure why it's doing this since the mobile styles should be kicking in. Any thoughts @SwampGuzzler ?

**Comment by richardbarad** [comment]
@KaylaKremer Is this ready for review? I just tested using this link http://alpha.blueraster.io/gfw-mapbuilder/502-increase-header-size/ on a mobile device and it looks like it is still using the desktop size.

![Screenshot_20190821-131753_Chrome](https://user-images.githubusercontent.com/40440743/63453207-1c062480-c416-11e9-88bf-e67ce7e9e6dd.jpg)

**Comment by KaylaKremer** [comment]
@richardbarad Not quite ready for review. I will let you know when it's ready!

**Comment by KaylaKremer** [comment]
@richardbarad Ok this is ready for review! I updated the build: http://alpha.blueraster.io/gfw-mapbuilder/502-increase-header-size/

My CSS was off by an indentation so looks like the mobile styles weren't being applied. It now should work. I set the mobile styles to kick in for anything less than `550px width`.

**Comment by richardbarad** [comment]
Looks good! This is approved.
