### ISSUE TITLE
Searching Display Field for MapService not working in 1.4.1.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#518]
If I:

1) Click on search in this build: http://alpha.blueraster.io/gfw-mapbuilder/new-report-consolidated-builds/default/?appid=277b92455c6c49059a95c9129be7baf9&l=en

2) Type Parc national des Kundelungu (The name of a national parc in the DRC)

3) Click enter

MapBuilder does not zoom to the feature of interest. There are also errors in the console. Attaching a video.

[Search-Mapservice.zip](https://github.com/wri/gfw-mapbuilder/files/3556216/Search-Mapservice.zip)

**Comment by KaylaKremer** [comment]
@richardbarad ,

I believe my fix for #517 also fixes this issue as well since they are giving the same error message. I tested it out with that build with the appId query string parameter and it worked for me. 

http://alpha.blueraster.io/gfw-mapbuilder/517-search-functionality-not-working/?appid=277b92455c6c49059a95c9129be7baf9&l=en

**Comment by richardbarad** [comment]
@KaylaKremer. This looks good. Thanks!
