### ISSUE TITLE
Fix styling on subscription scroll.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#545]
There seems to be a small styling issues in the subscription tools. It is currently not possible to use the scroll bar in the right hand corner to scroll through your subscriptions. See attached video. 

![2019-09-20 16_36_42-Mapbuilder Test App](https://user-images.githubusercontent.com/40440743/65357491-2bb78b00-dbc5-11e9-9dbf-3b94b3b0d9a2.png)

[subscription_bug.zip](https://github.com/wri/gfw-mapbuilder/files/3637639/subscription_bug.zip)

**Comment by KaylaKremer** [comment]
@richardbarad ,

It seems like this is an IE/Edge only issue as the scrolling works fine in both Chrome and Firefox. I believe I have fixed it, but do not have a Windows PC to test on. Let me know if this build works for you! http://alpha.blueraster.io/gfw-mapbuilder/545-subscription-modal-scroll/

**Comment by KaylaKremer** [comment]
@richardbarad Related note: I never saw the subscription modal until this ticket and couldn't help but notice that the styling is not the greatest in terms of the alignment and positioning. Would you like for me to make the subscription modal window look better?

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks for the follow-up. I do not think this is an Edge/IE as I was testing on Google Chrome.  After doing, I little more digging I think the issue is that the div for the close icon pointer is overlapping with the scroll bar. Thus, if you try to click on the scrollbar in the area where there is overlap it will not be possible to scrooldown. Please see the screenshot below.

![image](https://user-images.githubusercontent.com/40440743/65478702-bd8af680-de58-11e9-9ef5-149c91f82a34.png)

Would welcome improvements to the alignment and positioning of the modal! I am noticing that the update above may also have introduced a few alignment / styling issues through as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/40440743/65478928-8537e800-de59-11e9-8325-6f96a5a7d279.png)

**Comment by KaylaKremer** [comment]
@richardbarad , Thanks for letting me know that. I'll go ahead and fix the positioning of the close button as well as the rest of the modal so it doesn't interfere with the scroll.

I'm not quite sure why the alignment of the toggle buttons were affected since all I added was one CSS rule for IE that fixes a commonly known scroll bug, which I thought was the initial issue. But I will take out and see if that fixes it or figure out what is causing them not to align.

**Comment by KaylaKremer** [comment]
@richardbarad The build has been updated! http://alpha.blueraster.io/gfw-mapbuilder/545-subscription-modal-scroll/

I think I've now fixed the close button overlapping with the scrollbar. I also fixed the alignment of the toggle buttons that you pointed out. In addition, I've styled all of the subscription modal windows, such as the workflow the user goes through when creating a new subscription. I also added a hover highlight for the options under the `My GFW` menu button to provide better visual feedback for the user. Let me know what you think!

**Comment by richardbarad** [comment]
@KaylaKremer. Thanks for the quick updates. A few small comments:

1) Let's make sure that the x to close the modal does not overlap with the sides of the table (the grey lines)

2) Please also make sure there is the same amount of white space on both sides of the table

![2019-09-24 15_49_00-GFW Mapbuilder](https://user-images.githubusercontent.com/40440743/65545468-6da54180-dee3-11e9-9459-b4323baf7136.png)

3) Can we decrease the width of the box to match the width of the step where you name your subscription? This because most users will not need this much space to type an e-mail.
![E-mail_box](https://user-images.githubusercontent.com/40440743/65545618-b8bf5480-dee3-11e9-988c-a533dab70721.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

Build has been updated: http://alpha.blueraster.io/gfw-mapbuilder/545-subscription-modal-scroll/

I was able to fix all of your issues. Please note that for issue # 1 that you pointed out, there will need to be a little more white space on the right side to allow space for the x close button. Otherwise, it will either overlap the tables or the scrollbar! It looks like our default modal style has always had an additional 10px of padding to the right to accommodate for the close button.

**Comment by richardbarad** [comment]
Looks good!
