### ISSUE TITLE
Check why analysis does not load using geometries from map

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#567]
In this map: http://training.from-dc.com/maps/makuli

**If I:**

1. Click on a shape in the map

2. Run an analysis (i.e: Annual Tree Cover Loss in IFL)

3. The analysis returns an error:
![Analysis_erro](https://user-images.githubusercontent.com/40440743/66161539-85bf4400-e5fa-11e9-8b78-7b083d8538c2.png)

4. The shape also disappears from the map.

![image](https://user-images.githubusercontent.com/40440743/66161654-cae37600-e5fa-11e9-9cdf-3253e7d0a588.png)

Could you help investigate the cause here and what triggers the issue? The data is in a local projection so I wonder if that might be the case? If yes, is it an issue in MapBuilder or on the geostore side?

**Comment by KaylaKremer** [comment]
@richardbarad ,

It looks like the issue might be a combination of a Mapbuilder issue and geostore issue.

An `import` of `vega` in our `charts.js` file seems to have accidentally been removed. I am currently getting analysis errors on other builds due to this. I'm going to create a PR for this right away.

After I did that, the analyses ran fine with other configs. But for this Kenya config, it still is returning an error status code of 500. 

I will look at this with Lucas before our meeting today!

**Comment by richardbarad** [comment]
Richard going to ask team to try to republish data in webmercator.

**Comment by csphang** [comment]
@richardbarad Following-up on this. Was the team able to try republishing the data in webmercator?
