### ISSUE TITLE
The formatting of the scroll bar in the data tab does not match formatting of other scroll bars in app.

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#623]
The style of the scroll bar seems to have changed in this version. Please make sure style matches previous version and other scrollbars in the application
![Scroolbar](https://user-images.githubusercontent.com/40440743/67318286-4d17d980-f4d9-11e9-9561-b34831ab51e3.png)
.

**Comment by KaylaKremer** [comment]
@richardbarad ,

Test Build: http://alpha.blueraster.io/gfw-mapbuilder/623-scrollbar-styling

**Comment by richardbarad** [comment]
@KaylaKremer. The text is very close to the scroll bar and there is almost no padding. Are we able to revise so that it has the same padding as what was in the previous version (v1.4.1). https://cmr.forest-atlas.org/map?l=en

**Comment by KaylaKremer** [comment]
@richardbarad ,

Lucas went ahead and removed the padding because he thought it was better like that, but I told him I thought you had wanted the padding. I will definitely add it back in now!

**Comment by KaylaKremer** [comment]
@richardbarad ,

Just want clarification on this. Actually Lucas didn't remove anything, but we had discussed earlier about the padding for this, so I assumed wrong. We were discussing the gap that appears between the scrollbar and edge of the window:
<img width="342" alt="Screen Shot 2019-10-23 at 3 11 13 PM" src="https://user-images.githubusercontent.com/22095244/67426142-7141ec00-f5a7-11e9-8261-2fff0f9ffd3d.png">
Do you want this gap removed as well in addition to extra padding with the text? He thought it looked a little funny, but I wasn't sure if you wanted the gap so that it aligns with everything else? I can easily remove it too if you think that is best!

**Comment by richardbarad** [comment]
@KaylaKremer. On production sites (which use v.1.4.1) there is not gap so let's remove the gap and also add the padding.
![2019-10-23 15_15_24-Forest Atlas of DRC](https://user-images.githubusercontent.com/40440743/67426397-0218c780-f5a8-11e9-871f-9e2d879da5e6.png)

**Comment by KaylaKremer** [comment]
@richardbarad ,

New build for you to test! http://alpha.blueraster.io/gfw-mapbuilder/623-scrollbar-styling/

**Comment by richardbarad** [comment]
Can we remove the white space to the left and right of table and have the grey rows of the table go all the way across? The white space looks a little out of place to me and was to present in the previous version.

![table_whitespace](https://user-images.githubusercontent.com/40440743/67434459-46ac5f00-f5b8-11e9-8ee1-4938911dfd55.png)

**Comment by KaylaKremer** [comment]
Hi @richardbarad ,

Try out the build again. I updated it with your changes! http://alpha.blueraster.io/gfw-mapbuilder/623-scrollbar-styling/

**Comment by richardbarad** [comment]
@KaylaKremer. Look good and ready to merge!
