### ISSUE TITLE
Feature Service Legend bug

### ISSUE THREAD

**Issue by richardbarad** [wri/gfw-mapbuilder#643]
@richardbarad was doing some experimentation to see how well feature service layers perform in MapBuilder. Testing on this map: http://richard.teaches-yoga.com/map?l=en.

Currently, there were errors in the console related to the legend because the legend depended on the these `border` attributes from the symbols. Error in console shown below:

![2019-10-23 18_05_40-Hay Tao](https://user-images.githubusercontent.com/40440743/67497763-6e4d0700-f64c-11e9-9a90-cea01a16e783.png)

@SwampGuzzler revised the code so that we do not depend on these `border` attributes: http://alpha.blueraster.io/gfw-mapbuilder/richard-yoga-renderer-fix/

**A few questions:**

1. Was the issue that some of the legends for the feature service layers did not have an outline (only a fill)

2. And was the issue specific to configuring feature services via the configuration instead of through the webmap?

I think I have seen webmaps where we have feature services without an outline included in the configuration. We should deploy the fix above into 1.4.2 unless there might be changes which could risk breaking other apps!

**Comment by SwampGuzzler** [comment]
1. The cause was some feature symbol not having a border, which I have not seen before - now we check the existence of a border before using its style
2. I have never seen that error before -- was this coming from a Feature Service via the `configuration`?

@richardbarad  We will deploy this to `1.4.2` - the fix is simply a check and cannot cause harm, simply avoid styling a legend's `border` without a certain symbol property that it relies upon

**Comment by richardbarad** [comment]
@SwampGuzzler. Thanks! Sounds good!
